#include <stdio.h>

int main(int argc, char const *argv[])
{
	float fltPrice;
	float fltQuantity;
	
	// Initial statement, followed by price input.
	printf("\n\tThis program will calculate 'total revenue' generated by the sales of one item.\n");
    printf("\nInput price of item:    ");
    scanf("%f", &fltPrice);

    // Input of the quantity of the item sold.
    printf("\nInput quantity of item sold:    ");
    scanf("%f", &fltQuantity);

    // Printing of the total revenue. 
    printf("\nTotal revenue = (price * quantity)\n\nYour total revenue = %f \n\n", (fltPrice * fltQuantity));

	return 0;
}